[general]
fetch_interval=

[discord]
channel=
command_prefix="!"


[sqlite]
path=""


[chrome]
headleass=true
driver_path=""
loading_time=
interaction_time=

[scraper]
leaderboard_url=""
table_body_x=""
next_page_btn_x=""
total_display_count_x=""